Improve TIN validator
seegno/is-valid-ssn pull request #22
Opened 2022-11-07 18:56 UTC by KevinUphold

This PR aims to add more verifications for the TIN validator

2022-11-07 19:20 UTC, diogotorres97 requested changes

2022-11-07 19:20 UTC, diogotorres97 commented on src/index.js
> +const repitedNumbers = Array.from({ length: 9 - 0 + 1 }, (_, i) => i).map(current => String(current).repeat(9));
```suggestion
const repeatedNumbers = Array.from({ length: 9 - 0 + 1 }, (_, i) => i).map(current => String(current).repeat(9));
```

2022-11-08 22:42 UTC, diogotorres97 commented on src/index.js
> +const sequence = Array.from({ length: 9 - 0 + 1 }, (_, i) => i).reduce((acc, current) => acc + current, '').repeat(2);
```suggestion
const sequence = Array.from({ length: 10 }, (_, i) => i).reduce((acc, current) => acc + current, '').repeat(2);
```

2022-11-08 22:42 UTC, diogotorres97 commented on src/index.js
> +const sequence = Array.from({ length: 9 - 0 + 1 }, (_, i) => i).reduce((acc, current) => acc + current, '').repeat(2);
Not sure if we should include descending too

2022-11-08 22:44 UTC, diogotorres97 commented on src/index.js
> +const sequence = Array.from({ length: 9 - 0 + 1 }, (_, i) => i).reduce((acc, current) => acc + current, '').repeat(2);
https://apidocs.taxbit.com/docs/certifying-tax-documentation#taxid-string-required

> The taxId is fully ascending or descending e.g. "123456789" or "987654321"
> The taxId is a single digit repeated e.g. "111111111"

2022-11-09 14:33 UTC, afsampaio requested changes

2022-11-09 14:33 UTC, afsampaio commented on src/index.js
> +const repitedNumbers = Array.from({ length: 9 - 0 + 1 }, (_, i) => i).map(current => String(current).repeat(9));
Missing new line.

2022-11-09 14:33 UTC, afsampaio commented on src/index.js
> +const repeatedNumbers = Array.from({ length: 10 }, (_, i) => i).map(current => String(current).repeat(9));
Please add new line.

Please add comment explaining the "limitations".

2022-11-09 17:12 UTC, diogotorres97 commented on src/index.js
> + * Excludes repeated numbers as TIN e.g. 123456789.
```suggestion
 * Excludes repeated numbers as TIN e.g. 111111111.
```

2022-11-09 18:11 UTC, closed without merging